
services:
  db:
    image: postgres:16
    container_name: kc_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: kcuser
      POSTGRES_PASSWORD: kcpass
    volumes:
      - kc_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kcuser -d keycloak"]
      interval: 5s
      retries: 5

  keycloak:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: kc_sms_otp
    depends_on:
      db:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://db:5432/keycloak"
      KC_DB_USERNAME: kcuser
      KC_DB_PASSWORD: kcpass
      KC_HTTP_ENABLED: "true"

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      SMSIR_API_KEY:      "5gzpILYx5cjvsrpf1OUwa7b5iPjR7DhpluRZ2d67CSnq1Cxf"
      SMSIR_TEMPLATE_ID:  "647911"
      SMSIR_LINE_NUMBER:  "30002108001237"

      KC_LOG_LEVEL: DEBUG
      DEBUG: "true"
      DEBUG_PORT: "*:8787"
      DEBUG_SUSPEND: "n"
    ports:
      - "8080:8080"          # http://localhost:8080
      - "8787:8787"   # Debug port
    healthcheck:
      test: ["CMD", "/opt/keycloak/bin/kc.sh", "health", "check"]
      interval: 10s
      retries: 5

volumes:
  kc_db_data:
